# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_IP', models.CharField(max_length=20)),
                ('PLAIN_TEXT', models.CharField(max_length=4400)),
                ('USER_AGENT', models.CharField(max_length=1024)),
                ('ACCESS_TIME', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('file', models.FileField(null=True, upload_to=b'')),
            ],
        ),
    ]
