# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=20)),
                ('user_agent', models.CharField(max_length=1024)),
                ('access_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_msg', models.CharField(default='', max_length=4400)),
                ('input_key', models.CharField(default='GSSGSSGSSGSS', max_length=4400)),
                ('input_img', models.FileField(null=True, upload_to=b'')),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
