# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stegano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFileForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('input_img', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
