# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stegano', '0002_auto_20171204_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFileForm',
        ),
        migrations.AddField(
            model_name='saveinfo',
            name='input_img',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
