# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stegano', '0003_auto_20171204_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveinfo',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
