# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stegano', '0004_saveinfo_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveinfo',
            name='ENCRPY_KEY',
            field=models.CharField(default='GSSGSSGSSGSS', max_length=4400),
        ),
        migrations.AlterField(
            model_name='saveinfo',
            name='PLAIN_TEXT',
            field=models.CharField(default='', max_length=4400),
        ),
    ]
